In [ ]:
#Numpyのインポート
import numpy as np

#A,Bの定義
A = np.arange(6).reshape(3,2)
B = np.arange(8).reshape(2,4)

#行列の積
C = np.dot(A,B)

#結果の表示
print(C)

#最大値
Max = np.max(C)
Max

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]


47